modLoader="javafml"
loaderVersion="[31,)"
license="MIT"
issueTrackerURL="https://github.com/nikita488/ZYCraft/issues"

[[mods]]
modId="zycraft"
version="${file.jarVersion}"
displayName="ZYCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/zycraft"
authors="nikita488"
description='''
An attempt to return the feeling of XyCraft to the latest versions of Minecraft.
'''

[[dependencies.zycraft]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.zycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
